### ISSUE TITLE
email sending UnsupportedOperationException

### ISSUE THREAD

**Issue by downgoon** [downgoon/passport#13]
exception stack is as follows

``` java
 java.lang.UnsupportedOperationException: Method not yet implemented
     at javax.mail.internet.MimeMultipart.<init>(MimeMultipart.java:37)
     at org.apache.commons.mail.MultiPartEmail.createMimeMultipart(MultiPartEmail.java:505)
     at org.apache.commons.mail.MultiPartEmail.init(MultiPartEmail.java:176)
     at org.apache.commons.mail.MultiPartEmail.getContainer(MultiPartEmail.java:482)
     at org.apache.commons.mail.HtmlEmail.build(HtmlEmail.java:523)
     at org.apache.commons.mail.HtmlEmail.buildMimeMessage(HtmlEmail.java:508)
     at org.apache.commons.mail.Email.send(Email.java:1162)
```

**Comment by downgoon** [comment]
# find the problem 
``javax.mail.internet.MimeMultipart`` has been loaded but it's implementation may be out-of-date according to the exception stack mentioned above. so, search the target class ``javax.mail.internet.MimeMultipart`` by CTRL+SHIFT+T in Eclipse, we found two classes named the same name.

![MimeMultipart class found](https://cloud.githubusercontent.com/assets/23731186/21033471/6bb83ab0-bdeb-11e6-9de4-56671cb7e0eb.png)

# fix it
one is in ``resin-embed.jar`` and the other in ``geronimo-spec-javamail-1.3.1-rc3.jar``. it is very likely that one of them is out-of-date. kick off one of them from classpath, see the result. if not ok, kick off the other one.

finally, ``geronimo-spec-javamail-1.3.1-rc3.jar`` is out-of-date.

by the way, ``javax.mail.internet.MimeMultipart``  is the mail specification in J2EE. Resin is a web container compliance with J2EE, it provides javax.mail implenmetation.

**Comment by downgoon** [comment]
# a better way

to avoid depending on concrete web containers such as Resin or Tomcat, i decide to find an independent implementation and put it in ``$classpath``. search ``javax.mail.internet.MimeMultipart`` in [http://www.findjar.com](http://www.findjar.com/class/javax/mail/internet/MimeMultipart.html)  and get ``mail-1.4.jar``
