### ISSUE TITLE
profile update error

### ISSUE THREAD

**Issue by downgoon** [downgoon/passport#24]
``` java
Error creating bean with name 'restExceptionHandlerAction' defined in class path resource [applicationContext-action.xml]: Error setting property values; nested exception is org.springframework.beans.NotWritablePropertyException: Invalid property 'userManager' of bean class [io.downgoon.passport.web.action.RestExceptionHandlerAction]: Bean property 'userManager' is not writable or has an invalid setter method. Does the parameter type of the setter match the return type of the getter?
2016-12-22 17:44:51.303:WARN::/passport/profile-update.json
java.lang.IllegalStateException: Committed
	at org.eclipse.jetty.server.Response.resetBuffer(Response.java:1052)
	at org.eclipse.jetty.server.Response.sendError(Response.java:270)
	at org.apache.struts2.dispatcher.Dispatcher.sendError(Dispatcher.java:770)
	at org.apache.struts2.dispatcher.Dispatcher.serviceAction(Dispatcher.java:505)
	at org.apache.struts2.dispatcher.FilterDispatcher.doFilter(FilterDispatcher.java:395)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1322)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:473)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:119)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:514)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:226)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:920)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:403)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:184)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:856)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:117)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:247)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:151)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:114)
	at org.eclipse.jetty.server.Server.handle(Server.java:352)
	at org.eclipse.jetty.server.HttpConnection.handleRequest(HttpConnection.java:596)
	at org.eclipse.jetty.server.HttpConnection$RequestHandler.content(HttpConnection.java:1066)
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:805)
	at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:218)
	at org.eclipse.jetty.server.HttpConnection.handle(HttpConnection.java:426)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:510)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint.access$000(SelectChannelEndPoint.java:34)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:40)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:450)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by downgoon** [comment]
``RestExceptionHandlerAction`` is not a sub-class of ``BaseAction``
change

``` java
 <bean name="restExceptionHandlerAction" scope="prototype" class="io.downgoon.passport.web.action.RestExceptionHandlerAction"
	 	parent="baseAction">
		<property name="defaultExtension" value="json" />
</bean>
```
to

```
<bean name="restExceptionHandlerAction" scope="prototype" class="io.downgoon.passport.web.action.RestExceptionHandlerAction">
		<property name="restResultsHandler" ref="restResultsHandler" />
		<property name="defaultExtension" value="json" />
</bean>
```
